server:
  port: 8081

spring:
  application:
    name: gdg-service-auth
  cloud:
    config:
      enabled: false
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: sage-meliodas-GAZ-2026-secret-key-secure-2556bits
  expiration: 3600000