
# ============================================================
# CONFIGURATION DU SERVICE RÉSERVATIONS
# ============================================================

spring.application.name=service-reservations
server.port=8085

# ============================================================
# CONNEXION À POSTGRESQL
# ============================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/gdg_plateforme
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver


# ============================================================
# CONNEXION A LA BASE DE DONNEE EN LIGNE SUR SUPABASE
# ============================================================

# spring.datasource.url=jdbc:postgresql://aws-0-eu-west-3.pooler.supabase.com:6543/postgres
# spring.datasource.username=postgres.lfndwsyzicnktfxmgxhw
# spring.datasource.password=gdg@2026!Secure
# spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# CONNEXION À POSTGRESQL
# ============================================================

# spring.datasource.url=jdbc:postgresql://localhost:5432/gdg_auth
# spring.datasource.username=postgres
# spring.datasource.password=JOJOloj
# spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA / HIBERNATE
# ============================================================

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=reservations_schema
# 'validate' = vérifie que les tables existent

# ============================================================
# CONFIG SERVER
# ============================================================

spring.config.import=optional:configserver:http://localhost:8888

# ============================================================
# LOGGING
# ============================================================

logging.level.com.gdg.service.reservations=DEBUG

services.stock.url=http://localhost:8083
services.paiement.url=http://localhost:8086

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest