
# ============================================================
# CONFIGURATION DU SERVICE RÉSERVATIONS
# ============================================================

spring.application.name=service-reservations
server.port=${PORT:8085}

# ============================================================
# CONNEXION A LA BASE DE DONNEE EN LIGNE SUR SUPABASE
# ============================================================

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-0-eu-west-3.pooler.supabase.com:6543/postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres.lfndwsyzicnktfxmgxhw}
spring.datasource.password=${DATABASE_PASSWORD:gdg@2026!Secure}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# CONNEXION À POSTGRESQL
# ============================================================

# spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/gdg_plateforme}
# spring.datasource.username=${DATABASE_USERNAME:postgres}
# spring.datasource.password=${DATABASE_PASSWORD:12345}
# spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA / HIBERNATE
# ============================================================

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=reservations_schema
# 'validate' = vérifie que les tables existent

# ============================================================
# CONFIG SERVER
# ============================================================

spring.config.import=optional:${CONFIG_SERVER_URL:http://localhost:8888}

# ============================================================
# LOGGING
# ============================================================

logging.level.com.gdg.service.reservations=DEBUG

services.stock.url=${STOCK_SERVICE_URL:http://localhost:8083}
services.paiement.url=${PAIEMENT_SERVICE_URL:http://localhost:8086}

# spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
# spring.rabbitmq.port=${RABBITMQ_PORT:5672}
# spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
# spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.rabbitmq.host=${RABBITMQ_HOST:rat.rmq2.cloudamqp.com}
spring.rabbitmq.port=${RABBITMQ_PORT:5671}
spring.rabbitmq.username=${RABBITMQ_USERNAME:gpnrsqnc}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:4-5og49Fz8TrFQzwJAd9cYmxPzdn2RtP}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST:gpnrsqnc}
spring.rabbitmq.ssl.enabled=${RABBITMQ_SSL_ENABLED:true}
