# ============================================================
# CONFIGURATION DU SERVICE AGENCES
# ============================================================

spring.application.name=service-agences
server.port=8082

# ============================================================
# CONNEXION À POSTGRESQL
# ============================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/gdg_auth
spring.datasource.username=postgres
spring.datasource.password=JOJOloj
spring.datasource.driver-class-name=org.postgresql.Driver


# ============================================================
# CONNEXION A LA BASE DE DONNEE EN LIGNE SUR SUPABASE
# ============================================================

# spring.datasource.url=jdbc:postgresql://aws-0-eu-west-3.pooler.supabase.com:6543/postgres
# spring.datasource.username=postgres.lfndwsyzicnktfxmgxhw
# spring.datasource.password=gdg@2026!Secure
# spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA / HIBERNATE
# ============================================================

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=agences_schema
# ⚠️ 'validate' = vérifie que les tables existent, ne les modifie pas

# ============================================================
# CONFIG SERVER
# ============================================================

# spring.config.import=optional:configserver:
spring.cloud.config.enabled=false   

# ============================================================
# UPLOAD DES FICHIERS
# ============================================================

app.upload.dir=./uploads
app.upload.base-url=/uploads
gdg.auth.url=http://localhost:8081
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ============================================================
# LOGGING
# ============================================================

logging.level.com.gdg.service_agences=DEBUG