spring.application.name=gdg-service-paiement
server.port=8085

# ══════════════════════════════════════
# CONFIG LOCAL (active pendant le développement)
# ══════════════════════════════════════

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# ══════════════════════════════════════
# CONFIG SUPABASE (à activer au déploiement)
# Décommente ces lignes et commente celles du dessus
# ══════════════════════════════════════
#spring.datasource.url=jdbc:postgresql://db.lfndwsyzicnktfxmgxhw.supabase.co:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=TonMotDePasseSupabase

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=paiement_schema
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect